### PR TITLE
Embed Apple root and intermediate certificates into quill binary

### LINKED ISSUE #8: Embed the Apple root and intermediate certificates directly into quill
Today we require that users run `quill attach-chain <p12>` to craft a new p12 file that has the full cert chain for use in signing. Without this signing verification will fail. Another way to do this is to bake the Apple certs directly into quill such that the full chain (if it does not already exist in the p12) could be looked up at runtime.

The `codesign` utility does something like this by looking up the remaining certs in the chain in the system keychain. This won't be possible for all end users of quill since they may not be running on a mac (there is no reason to assume that apple root certs will be on a linux box, for instance).

### LINKED ISSUE #16: Signing Is Failing for P12 With Chain File
## What Happened

I'm trying to work through the signing process with a developer id application cert (p12).
I've followed the directions and am not able to get notarization to correctly work.

The signing continues without error, but upon notarization I get a few errors.

**How to reproduce it (as minimally and precisely as possible)**:

- When testing against my binary (produced by goreleaser), this command: `codesign -vvv --deep --strict $artifact` returns `CSSMERR_TP_NOT_TRUSTED In architecture: x86_64`.
- `spctl -vvv --assess --type exec $artifact` returns `CSSMERR_TP_NOT_TRUSTED`.

The notarization attempt responds with 2 errors in the json response:

```json
"issues": [
    {
      "severity": "error",
      "code": null,
      "path": "myapp-darwin-amd64",
      "message": "The signature of the binary is invalid.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087735",
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "myapp-darwin-amd64",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087733",
      "architecture": "x86_64"
    }
  ]
```

- Running `quill describe` against my original and `-with-chain` p12 file: `        * unable to parse single-arch binary: unable to parse macho formatted file with blacktop: invalid magic number in record at byte 0x0`.

## Other Troubleshooting Steps I've Taken

- Validated apple CA/WWWDR/timestamp certs are installed.
- Validated the trust settings are set to Defaults, not overridden to Always Trust.
- Confirmed from docs the Developer ID cert is the correct type for signing binaries such as CLI tools.

## Summary

I've gotten quill to mark the file as signed with a non-apple developer cert (pfx/p12), but what I understand is that for mac Gatekeeper to allowlist the app I need to use only an Apple cert. I've iterated on this for days and not sure where else to go with it. 

## Troubleshooting Script in Progress

```shell
export QUILL_P12_PASSWORD=''
export QUILL_SIGN_PASSWORD=${QUILL_P12_PASSWORD}

export P12_APP=pathtodeveloperid-application-cert.p12
export P12_WITH_CHAIN=pathtodeveloperid-application-cert-with-chain.p12
export QUILL_SIGN_P12=$P12_WITH_CHAIN

# ensure full chain is attached for the sign/notarization process via quill
quill p12 attach-chain $P12_APP


quill sign-and-notarize --p12 $P12_WITH_CHAIN \
    --notary-key-id 'notarykeyid' \
    --notary-key 'pathtoAuthKey_zzzzzzz.p8' \
    --notary-issuer 'guidplacedhere' \
    $artifact

# Tried explicit timestamp add and no difference, so removed.
# --timestamp-server 'http://timestamp.apple.com/ts01' \

# other follow-up commands I've used. 
security find-identity
codesign -vvv --deep --strict $artifact
spctl -vvv --assess --type exec $artifact

```

### PR DESCRIPTION
**Pull request by wagoodman**
This PR makes the following changes to quill:
- Fails signing if certificate verification fails (which now requires the full chain). Previously verification would be skipped with a warning when the full chain was not found. Now there is an error indicating the chain is missing. This can be turned off with the `QUILL_SIGN_FAIL_WITHOUT_FULL_CHAIN` env var set to `false`.
- Embeds all of the root and intermediate certificates found from https://www.apple.com/certificateauthority/ via a `go generate` step. These certificates are checked into the repo. Note: no automation updates these certificates, they will need to be updated manually and checked in with `make update-apple-certs`
- Adds new `quill embedded-certificates` command to enumerate the Apple certificates embedded in the quill binary
- renames the `pem` package to `pki` (more accurate, especially with the current additions)
- splits the `pki` packages into `load` for loading material from sources and `certchain` for operating on a cert store or chain.

TODO:
- [x] add test that shows failure with single cert during signing and another test that sets `QUILL_SIGN_FAIL_WITHOUT_FULL_CHAIN` to `false` and shows the previous test steps pass.
- [x] refactor the embedded store behind an interface to make testing easier -- add unit tests for `pki.FindRemainingChainCerts` to show that the embedded lookup works as expected with test-fixture certs.
- [x] update README.md to show that the attach-chain step is no longer necessary (but also show it's necessary for non-apple roots being used)
- [x] maybe rename the `quill apple-certs` command? [renamed to `embedded-certificates`]

Closes #8 
Closes #16

### CODE REVIEW

File: quill/pki/load/private_key.go [hunk 1]
```diff
@@ -10,10 +10,10 @@ import (
 	"github.com/anchore/quill/internal/log"
 )
 
-func loadPrivateKey(path string, password string) (crypto.PrivateKey, error) {
+func NewPrivateKey(path string, password string) (crypto.PrivateKey, error) {
```
Comment (kzantow) [inline quill/pki/load/private_key.go:13]: similar comment is this really "New"?

**Review by kzantow — APPROVED** [review]
LGTM

File: quill/pki/load/private_key.go (hunk 1 above)
Comment (wagoodman) [reply quill/pki/load/private_key.go]: I went ahead and made the same adjustments to the remaining helper functions in this package
